# Generated by Django 6.0.6 on 2026-06-18 09:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('course', models.CharField(max_length=100)),
                ('batch_month', models.CharField(blank=True, default='', max_length=100)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('fileLink', models.FileField(blank=True, null=True, upload_to='assignments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('course_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('img', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('imageUrl', models.URLField(blank=True, default='', max_length=500)),
                ('duration', models.CharField(blank=True, default='90 days', max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('targetCourse', models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Java Full Stack', 'Java Full Stack'), ('Python Development', 'Python Development'), ('MERN Stack', 'MERN Stack'), ('SQL & Data Analytics', 'SQL & Data Analytics'), ('Software Development', 'Software Development'), ('Testing', 'Testing'), ('UI/UX Design', 'UI/UX Design'), ('Devops', 'Devops'), ('DevOps', 'DevOps'), ('AI/ML', 'AI/ML'), ('AL/ML', 'AL/ML'), ('Data Science', 'Data Science'), ('Soft Skills', 'Soft Skills')], max_length=100)),
                ('batchMonth', models.CharField(choices=[('All Batches', 'All Batches'), ('June Batch', 'June Batch'), ('Sept Batch', 'Sept Batch'), ('Dec Batch', 'Dec Batch')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessType', models.CharField(choices=[('Demo Class (Slot Booking)', 'Demo Class'), ('Full Course (Fully Paid)', 'Full Course')], default='Demo Class (Slot Booking)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecordedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('videoLink', models.URLField()),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('targetCourse', models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Java Full Stack', 'Java Full Stack'), ('Python Development', 'Python Development'), ('MERN Stack', 'MERN Stack'), ('SQL & Data Analytics', 'SQL & Data Analytics'), ('Software Development', 'Software Development'), ('Testing', 'Testing'), ('UI/UX Design', 'UI/UX Design'), ('Devops', 'Devops'), ('DevOps', 'DevOps'), ('AI/ML', 'AI/ML'), ('AL/ML', 'AL/ML'), ('Data Science', 'Data Science'), ('Soft Skills', 'Soft Skills')], max_length=100)),
                ('batchMonth', models.CharField(choices=[('All Batches', 'All Batches'), ('June Batch', 'June Batch'), ('Sept Batch', 'Sept Batch'), ('Dec Batch', 'Dec Batch')], max_length=100)),
                ('accessType', models.CharField(choices=[('Demo Class (Slot Booking)', 'Demo Class'), ('Full Course (Fully Paid)', 'Full Course')], default='Demo Class (Slot Booking)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('driveLink', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('targetCourse', models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Java Full Stack', 'Java Full Stack'), ('Python Development', 'Python Development'), ('MERN Stack', 'MERN Stack'), ('SQL & Data Analytics', 'SQL & Data Analytics'), ('Software Development', 'Software Development'), ('Testing', 'Testing'), ('UI/UX Design', 'UI/UX Design'), ('Devops', 'Devops'), ('DevOps', 'DevOps'), ('AI/ML', 'AI/ML'), ('AL/ML', 'AL/ML'), ('Data Science', 'Data Science'), ('Soft Skills', 'Soft Skills')], max_length=100)),
                ('batchMonth', models.CharField(choices=[('All Batches', 'All Batches'), ('June Batch', 'June Batch'), ('Sept Batch', 'Sept Batch'), ('Dec Batch', 'Dec Batch')], max_length=100)),
                ('accessType', models.CharField(choices=[('Demo Class (Slot Booking)', 'Demo Class'), ('Full Course (Fully Paid)', 'Full Course')], default='Demo Class (Slot Booking)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(default='0000000000', max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('collegeName', models.CharField(blank=True, max_length=200, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('degreeType', models.CharField(max_length=50)),
                ('passOutYear', models.CharField(max_length=10)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('enrollmentType', models.CharField(choices=[('Training', 'Training'), ('Internship', 'Internship'), ('Training+Internship', 'Training+Internship')], default='Training', max_length=30)),
                ('courseSpecialization', models.CharField(default='Not Specified', max_length=100)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Hybrid', 'Hybrid')], default='Online', max_length=20)),
                ('couponCode', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentStatus', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('assigned_course', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileLink', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('status', models.CharField(default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='App.assignment')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='App.student')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('batch', models.CharField(max_length=100)),
                ('meeting_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('ENDED', 'Ended')], default='SCHEDULED', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_classes', to='App.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('course', models.CharField(max_length=100)),
                ('batch_month', models.CharField(blank=True, default='', max_length=100)),
                ('fileLink', models.FileField(blank=True, null=True, upload_to='notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(blank=True, default='', max_length=200)),
                ('startDate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='App.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.trainer'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('items', models.JSONField()),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('enrollment_type', models.CharField(choices=[('full', 'Full Payment'), ('installment', 'Installment'), ('slot', 'Seat Booking')], max_length=20)),
                ('batch_date', models.CharField(max_length=50)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('card', 'Card'), ('netbanking', 'Net Banking')], max_length=20)),
                ('billing_country', models.CharField(max_length=50)),
                ('billing_state', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='App.batch')),
                ('assigned_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enrollments', to='App.trainer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.userregister')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('status', models.CharField(default='Absent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.student')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.trainer')),
            ],
            options={
                'unique_together': {('student', 'attendance_date', 'batch')},
            },
        ),
    ]
