# Generated by Django 6.0.6 on 2026-06-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, default='Software Development', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, default='4999', max_length=50),
        ),
    ]
