# Generated by Django 6.0.3 on 2026-06-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_trainer_assignment_batch_month_note_batch_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Java Full Stack', 'Java Full Stack'), ('Python Development', 'Python Development'), ('MERN Stack', 'MERN Stack'), ('SQL & Data Analytics', 'SQL & Data Analytics'), ('Software Development', 'Software Development'), ('Testing', 'Testing'), ('UI/UX Design', 'UI/UX Design'), ('Devops', 'Devops'), ('DevOps', 'DevOps'), ('AI/ML', 'AI/ML'), ('AL/ML', 'AL/ML'), ('Data Science', 'Data Science'), ('Soft Skills', 'Soft Skills')], max_length=100),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='targetCourse',
            field=models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Java Full Stack', 'Java Full Stack'), ('Python Development', 'Python Development'), ('MERN Stack', 'MERN Stack'), ('SQL & Data Analytics', 'SQL & Data Analytics'), ('Software Development', 'Software Development'), ('Testing', 'Testing'), ('UI/UX Design', 'UI/UX Design'), ('Devops', 'Devops'), ('DevOps', 'DevOps'), ('AI/ML', 'AI/ML'), ('AL/ML', 'AL/ML'), ('Data Science', 'Data Science'), ('Soft Skills', 'Soft Skills')], max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='course',
            field=models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Java Full Stack', 'Java Full Stack'), ('Python Development', 'Python Development'), ('MERN Stack', 'MERN Stack'), ('SQL & Data Analytics', 'SQL & Data Analytics'), ('Software Development', 'Software Development'), ('Testing', 'Testing'), ('UI/UX Design', 'UI/UX Design'), ('Devops', 'Devops'), ('DevOps', 'DevOps'), ('AI/ML', 'AI/ML'), ('AL/ML', 'AL/ML'), ('Data Science', 'Data Science'), ('Soft Skills', 'Soft Skills')], max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='fileLink',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
        migrations.AlterField(
            model_name='recordedclass',
            name='targetCourse',
            field=models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Java Full Stack', 'Java Full Stack'), ('Python Development', 'Python Development'), ('MERN Stack', 'MERN Stack'), ('SQL & Data Analytics', 'SQL & Data Analytics'), ('Software Development', 'Software Development'), ('Testing', 'Testing'), ('UI/UX Design', 'UI/UX Design'), ('Devops', 'Devops'), ('DevOps', 'DevOps'), ('AI/ML', 'AI/ML'), ('AL/ML', 'AL/ML'), ('Data Science', 'Data Science'), ('Soft Skills', 'Soft Skills')], max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='targetCourse',
            field=models.CharField(choices=[('All Courses', 'All Courses'), ('React Full Stack Development', 'React Full Stack Development'), ('Java Full Stack', 'Java Full Stack'), ('Python Development', 'Python Development'), ('MERN Stack', 'MERN Stack'), ('SQL & Data Analytics', 'SQL & Data Analytics'), ('Software Development', 'Software Development'), ('Testing', 'Testing'), ('UI/UX Design', 'UI/UX Design'), ('Devops', 'Devops'), ('DevOps', 'DevOps'), ('AI/ML', 'AI/ML'), ('AL/ML', 'AL/ML'), ('Data Science', 'Data Science'), ('Soft Skills', 'Soft Skills')], max_length=100),
        ),
    ]
