# Generated by Django 6.0.6 on 2026-06-19 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('course_id', models.CharField(blank=True, help_text='Identifier of the course associated with this payment', max_length=100, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('checkout_data', models.JSONField(blank=True, help_text='Checkout metadata: items, enrollment_type, batch_date, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='App.student')),
            ],
        ),
    ]
