# Generated by Django 6.0.3 on 2026-06-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_assignment_course_alter_liveclass_targetcourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='note',
            name='course',
            field=models.CharField(max_length=100),
        ),
    ]
