# Generated by Django 6.0.6 on 2026-06-17 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_onlineclass'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='batch',
                    name='assigned_mentor',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='App.trainer'),
                ),
            ],
            database_operations=[]
        ),
        migrations.AddField(
            model_name='onlineclass',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
